### ISSUE TITLE
Base64_decode

### ISSUE THREAD

**Issue by sebastianblum** [8p/guzzle-wsse-middleware#4]
hello!

https://github.com/8p/guzzle-wsse-middleware/blob/master/src/EightPoints/Guzzle/WsseAuthMiddleware.php#L151

My APIs doesn't work so, because base64_decode of a not encodes string is null.

Other implementations encode the nonce base64, then we have to change this method

    return hash('sha512', uniqid(true));

    return base64_encode(hash('sha512', uniqid(true)));

**Comment by florianpreusner** [comment]
Hi!

Sounds fine for me and makes sense.

Best regards
Florian

**Comment by florianpreusner** [comment]
Changed: https://github.com/8p/guzzle-wsse-middleware/commit/362a243d15901ff6e3e8bce91e6d1dc172c5035c

**Comment by florianpreusner** [comment]
Created new version https://github.com/8p/guzzle-wsse-middleware/releases/tag/v4.0.0
