### ISSUE TITLE
Introduce offset for created-timestamp

### ISSUE THREAD

**Issue by mathielen** [8p/guzzle-wsse-middleware#5]
Hi there,
I'm running into problems where the timestamp used for creating the digest is in the future from the api-server side's perspective.
Even though the client and the server are using the same NTP time synchronization services, sometimes the client is +1 second beyond. This results in an error.
Any chance of introducing a (negative) offset-configuration in your middleware?

I did a quick fix like this, to be sure the client's timestamp is 30s in the past:
```php
$createdAt = date('c', time()-30);
```

Best regards

**Comment by florianpreusner** [comment]
Hi,

added a functionality to set the createdAt time by a setter optionally:
```php
$wsse->setCreatedAt(new \DateTime('-30 seconds'));
```

Best regards
Florian

**Comment by florianpreusner** [comment]
Created version 4.1.0: 
https://github.com/8p/guzzle-wsse-middleware/releases/tag/v4.1.0

**Comment by mathielen** [comment]
Awesome! Thank you!

**Comment by mathielen** [comment]
Hmm. I think the solution still have some problems...

First, I am working with your fantastic https://github.com/8p/GuzzleBundle. Unfortunately there's no easy way to apply the setCreatedAt-call to the embedded wsse middleware.
But I think the bigger problem is this: I would have to call setCreatedAt each time i'm doing a guzzle call. If I dont, and have a somewhat long(er) running process, the timestamp will eventually be quite old, which might cause another server-side exception.
What do you think about setting a "time-expression" instead of the \DateTime object? So when the attached callable is called, you create a new \DateTime()-object based on the expression. Which is "now" by default, but could be "-10 seconds" - and its just a string.

What do you think about it?

**Comment by florianpreusner** [comment]
Yeah, you are right. The current implementation can lead to this problem. I like the idea of having a expression because you are very flexible with that solution 👍 

I'm going to implement that.

**Comment by mathielen** [comment]
Can you give me a hint how I would call the getCreatedAtTimeExpression() with the guzzle-bundle?
I think its not really possible without hacking the bundle: https://github.com/8p/GuzzleBundle/blob/master/DependencyInjection/GuzzleExtension.php#L123

Thanks

**Comment by florianpreusner** [comment]
Yes, right now it is not supported by this bundle. I will add a possibility to set the expression in the configuration. 

It would be great if you can add a feature request in the bundle repository cause the middleware has no relation to the bundle, but the bundle has a relation to this middleware. Just to cleanup everything.

**Comment by mathielen** [comment]
Sure. Will do!
